#!/usr/bin/env bash

set -e
set -x

# install skdownscale
/srv/conda/envs/notebook/bin/python -m pip install -e .

# install jupyter labextensions
jupyter labextension install --clean \
    @jupyter-widgets/jupyterlab-manager \
    dask-labextension

# add dask config
mkdir -p ${KERNEL_PYTHON_PREFIX}/etc/dask
cp .binder/dask_config.yaml ${KERNEL_PYTHON_PREFIX}/etc/dask/dask.yaml
