#!/usr/bin/env bash

set -e

# install skdownscale
pip install . --no-deps
pip install --upgrade git+git://github.com/dcherian/xarray.git@map-blocks-dask-args --no-deps

# install jupyter labextensions
jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager \
                            dask-labextension
