#!/usr/bin/env bash

# install skdownscale
pip install -e .

# install jupyter labextensions
jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager \
                            dask-labextension
