import datetime

import skdownscale

current_year = datetime.datetime.now().year
project = 'scikit-downscale'
copyright = f'2020-{current_year}, Joe Hamman & Contributors'
author = f'{project} Contributors'

release = skdownscale.__version__
version = '.'.join(release.split('.')[:2])


extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.doctest',
    'sphinx.ext.extlinks',
    'sphinx.ext.napoleon',
    'numpydoc',
    'myst_nb',
    'sphinxext.opengraph',
    'sphinx_copybutton',
    'sphinx_design',
]

# MyST config
myst_enable_extensions = ['amsmath', 'colon_fence', 'deflist', 'html_image']
myst_url_schemes = ['http', 'https', 'mailto']

# Jupyter notebook config
nb_execution_mode = 'auto'  # Don't execute notebooks during build
nb_execution_allow_errors = False
nb_execution_timeout = 300

# sphinx-copybutton configurations
copybutton_prompt_text = r'>>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: '
copybutton_prompt_is_regexp = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# Autosummary pages will be generated by sphinx-autogen instead of sphinx-build
autosummary_generate = True
autosummary_ignore_module_all = False
autodoc_typehints = 'none'
autodoc_member_order = 'groupwise'
autodoc_default_options = {
    'members': True,
    'inherited-members': False,
    'show-inheritance': True,
}

# Napoleon configurations

napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_use_param = False
napoleon_use_rtype = False
napoleon_preprocess_types = True

# Numpydoc configurations
numpydoc_show_class_members = False
numpydoc_class_members_toctree = False
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'


exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '**.ipynb_checkpoints']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


html_theme = 'furo'
html_title = ''
html_context = {
    'github_user': 'pangeo-data',
    'github_repo': 'scikit-downscale',
    'github_version': 'main',
    'doc_path': 'docs',
}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'skdownscaledoc'
html_last_updated_fmt = '%b %d, %Y'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {}
latex_documents = [
    (
        master_doc,
        'skdownscale.tex',
        'scikit-downscale Documentation',
        'Joe Hamman & Contributors',
        'manual',
    )
]


# -- Options for manual page output ------------------------------------------


man_pages = [(master_doc, 'scikit-downscale', 'scikit-downscale Documentation', [author], 1)]


# -- Options for Texinfo output ----------------------------------------------
texinfo_documents = [
    (
        master_doc,
        'scikit-downscale',
        'scikit-downscale Documentation',
        author,
        'scikit-downscale',
        'Statistical Downscaling in Python',
        'Miscellaneous',
    )
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'xarray': ('https://docs.xarray.dev/en/stable/', None),
    'scikit-learn': ('https://scikit-learn.org/stable/', None),
}
